name: 'Release Assets Finder'
description: 'Fetch release assets download URLs from a GitHub repository'
author: 'Limitex'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: download
  color: blue

# Define your inputs here.
inputs:
  owner:
    description: 'Repository owner'
    required: true
  repo:
    description: 'Repository name'
    required: true
  pattern:
    description: 'Regular expression pattern to filter assets'
    required: false

# Define your outputs here.
outputs:
  releases:
    description:
      'JSON string containing matching asset download URLs grouped by release'

runs:
  using: 'node20'
  main: 'dist/index.js'
