name: 'Get Release Assets'
description: 'Fetch release assets download URLs from a GitHub repository'
author: Your name or organization here

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  owner:
    description: 'Repository owner'
    required: true
  repo:
    description: 'Repository name'
    required: true
  pattern:
    description: 'Regular expression pattern to filter assets'
    required: false

# Define your outputs here.
outputs:
  assets:
    description:
      'JSON string containing matching asset download URLs grouped by release'

runs:
  using: 'node20'
  main: 'dist/index.js'
